module.exports = {
  Profanity: [/(profanity|obscenity)/, /propaganda films‎/],
  Weapons: [
    /semi-automatic/,
    /rilfes/,
    /firearms/,
    /pistols/,
    /shotguns/,
    /granades/,
    /knives/,
    /weapons and ammunition/,
    / weapons$/,
    /chemical weapon/,
    /explosives/,
    /flamethrowers/
  ],
  Violence: [
    /suicide methods/,
    /\bbombing/,
    /\bbombers/,
    /. tactics/,
    /serial killers/,
    /murder in ./,
    /necrophiles/,
    /terrorist incidents/,
    /cannibals/,
    /\bbombing/,
    /mass shootings/,
    /stabbing attacks/,
    /arson attacks/,
    /lynching/,
    /drone strikes/,
    /assassinations/,
    /hostage taking/
  ],
  Sexuality: [
    /bdsm/,
    /fetish/,
    /incest/,
    /breast/,
    /nipple/,
    /penis/,
    /scrotum/,
    /nude sculptures/,
    /naturis[mt]/,
    /genital/,
    /masturbation/,
    /ejaculation/,
    /orgasm/,
    /erotica/,
    /strip clubs/,
    /camming/,
    /\bsex toys/,
    /pornographic/,
    /pornography/,
    /erotic/,
    /bdsm/,
    /human reproduction/,
    /\bsexuality\b/,
    /\brape in ./,
    /sexual abuse/,
    /dominatrices/,
    /brothels/,
    /red-light districts/,
    /courtesans/,
    /\brapists\b/,
    /prostitutes/,
    /prostitution/,
    /sex workers/,
    /nudity/,
    /erotic dancers/
  ]
}
